# Generated by Django 5.2.5 on 2025-08-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='attendance_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='attendance_username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
