# Generated by Django 5.2.5 on 2025-08-28 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_company_attendance_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='attendance_password',
        ),
        migrations.RemoveField(
            model_name='company',
            name='attendance_username',
        ),
    ]
