# Generated by Django 4.2.23 on 2025-07-03 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0004_company_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
