# Generated by Django 5.2.5 on 2025-08-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0005_alter_company_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='vtu_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
