# Generated by Django 4.2.23 on 2025-07-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0005_alter_company_options_remove_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='fees',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
