# Generated by Django 5.2.5 on 2025-08-31 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0006_attendance_vtu_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='approval_letter_got',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='approval_letter_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='bonafied_got',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='bonafied_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='undertaking_form_got',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='undertaking_form_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
