# Generated by Django 4.2.23 on 2025-07-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0006_company_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fee',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
