# Generated by Django 4.2.23 on 2025-07-04 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0007_student_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='applied_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.company'),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('roll_number', 'applied_company')},
        ),
    ]
