# Generated by Django 5.2.5 on 2025-08-31 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0007_student_approval_letter_got_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='approval_letter_got',
        ),
        migrations.RemoveField(
            model_name='student',
            name='approval_letter_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='bonafied_got',
        ),
        migrations.RemoveField(
            model_name='student',
            name='bonafied_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='undertaking_form_got',
        ),
        migrations.RemoveField(
            model_name='student',
            name='undertaking_form_id',
        ),
    ]
