# Generated by Django 5.2.5 on 2025-08-31 22:53

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0008_remove_student_approval_letter_got_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='approval_letter',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='approval_letter_got',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='bonafide_letter',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='bonafide_letter_got',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='undertaking_letter',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='undertaking_letter_got',
            field=models.BooleanField(default=False),
        ),
    ]
