# Generated by Django 5.2.5 on 2025-09-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0009_student_approval_letter_student_approval_letter_got_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='downloadable_files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('file_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
