# Generated by Django 4.2.23 on 2025-07-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0009_company_cgpa_company_description_company_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='skill_required',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
