# Generated by Django 4.2.23 on 2025-07-05 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0010_alter_company_description_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
