# Generated by Django 4.2.23 on 2025-07-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0012_company_active_alter_company_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
