# Generated by Django 4.2.23 on 2025-07-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0013_sitesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Announcement', models.CharField(max_length=200)),
            ],
        ),
    ]
