# Generated by Django 4.2.23 on 2025-07-06 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0014_announcement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcement'},
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='Announcement',
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='message',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
