# Generated by Django 4.2.23 on 2025-07-06 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0015_alter_announcement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': 'Announcement', 'verbose_name_plural': 'Announcements'},
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='message',
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_message1_active',
            field=models.BooleanField(default=False, verbose_name='Show Message 1'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_message2_active',
            field=models.BooleanField(default=False, verbose_name='Show Message 2'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='message1',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Message 1'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='message2',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Message 2'),
        ),
    ]
