# Generated by Django 4.2.23 on 2025-07-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0016_alter_announcement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='message1_color',
            field=models.CharField(choices=[('success', 'Success - Green'), ('info', 'Info - Blue'), ('warning', 'Warning - Orange'), ('danger', 'Error - Red')], default='success', max_length=10, verbose_name='Message 1 Color'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='message2_color',
            field=models.CharField(choices=[('success', 'Success - Green'), ('info', 'Info - Blue'), ('warning', 'Warning - Orange'), ('danger', 'Error - Red')], default='warning', max_length=10, verbose_name='Message 2 Color'),
        ),
    ]
