# Generated by Django 4.2.23 on 2025-07-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0017_announcement_message1_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='message1_color',
            field=models.CharField(choices=[('green', 'Success - Green'), ('blue', 'Info - Blue'), ('orange', 'Warning - Orange'), ('red', 'Error - Red')], default='green', max_length=10, verbose_name='Message 1 Color'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='message2_color',
            field=models.CharField(choices=[('green', 'Success - Green'), ('blue', 'Info - Blue'), ('orange', 'Warning - Orange'), ('red', 'Error - Red')], default='orange', max_length=10, verbose_name='Message 2 Color'),
        ),
    ]
