# Generated by Django 4.2.23 on 2025-07-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0018_alter_announcement_message1_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('student_name', models.CharField(max_length=100, verbose_name='Name of the Student')),
                ('vtu_number', models.CharField(max_length=20, verbose_name='VTU Number')),
                ('contact_number', models.CharField(max_length=15, verbose_name='Contact Number of the Student')),
                ('department', models.CharField(blank=True, choices=[('Artificial Intelligence (AI) and Data Science', 'Artificial Intelligence (AI) and Data Science'), ('Artificial Intelligence and Machine Learning', 'Artificial Intelligence and Machine Learning'), ('Computer Science & Engineering', 'Computer Science & Engineering'), ('Computer Science and Engineering (Artificial Intelligence and Machine Learning)', 'Computer Science and Engineering (Artificial Intelligence and Machine Learning)'), ('Computer Science and Engineering (Cyber Security)', 'Computer Science and Engineering (Cyber Security)'), ('Computer Science and Engineering (Data Science)', 'Computer Science and Engineering (Data Science)'), ('Computer Science and Design', 'Computer Science and Design'), ('Information Technology', 'Information Technology')], max_length=150, null=True, verbose_name='Department of the Student')),
                ('industry_name', models.CharField(max_length=100, verbose_name='Name of the Industry')),
                ('industry_location', models.CharField(max_length=100, verbose_name='Location of the Industry')),
                ('domain_of_work', models.CharField(max_length=100, verbose_name='Domain of Work')),
                ('industry_category', models.CharField(max_length=100, verbose_name='Category the Industry')),
                ('referal_person_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name of the Referal Person')),
                ('referal_person_designation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Designation of the Referal Person')),
                ('referal_person_phone_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Mobile Number of the Referal Person')),
                ('referal_person_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email of the Referal Person')),
                ('industry_website', models.URLField(blank=True, null=True, verbose_name='Website Link of the Industry')),
                ('industry_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Industry Contact Email')),
                ('industry_phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Industry Contact Phone')),
                ('stipend_provided', models.CharField(max_length=3, verbose_name='Any Stipend Provided from the Industry?')),
                ('stipend_amount', models.CharField(blank=True, max_length=20, null=True, verbose_name='If Yes, How much Stipend?')),
                ('fees_required', models.CharField(max_length=3, verbose_name='Is there any need to pay fees to acquire the Internship?')),
                ('fees_amount', models.CharField(blank=True, max_length=20, null=True, verbose_name='If yes, How much fees?')),
                ('application_approved', models.CharField(choices=[('YES', 'Approved'), ('NO', 'Not Approved'), ('PENDING', 'Pending')], default='PENDING', max_length=10, verbose_name='Application Approval Status')),
                ('approval_message', models.TextField(blank=True, null=True, verbose_name='Message Regarding Approval Status')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('problem', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
