# Generated by Django 4.2.23 on 2025-07-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0019_internshipapplication_userreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipapplication',
            name='application_approved',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Not Approved'), ('PENDING', 'Pending')], default='PENDING', max_length=10, verbose_name='Application Approval Status'),
        ),
    ]
