# Generated by Django 4.2.23 on 2025-07-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0020_alter_internshipapplication_application_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('report_status', models.CharField(choices=[('REPORTED', 'Reported'), ('NOT_REPORTED', 'Not Reported')], default='NOT_REPORTED', max_length=15)),
            ],
        ),
    ]
