# Generated by Django 4.2.23 on 2025-07-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0021_studentreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreport',
            name='report_status',
            field=models.CharField(choices=[('REPORTED', 'Reported to the Company'), ('NOT_REPORTED', 'Not Reported to the Company'), ('PENDING', 'repoting on 21 july')], max_length=20),
        ),
    ]
