# Generated by Django 5.2.5 on 2025-08-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0022_alter_studentreport_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='house',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
